### ISSUE TITLE
schedule .ics feed seems to have wrong timezone

### ISSUE THREAD

**Issue by aspiers** [OpenStackweb/openstack-org#145]
I have just tested the newly merged iCal feed functionality mentioned in #133, by importing into my Google Calendar.  It works beautifully, except that the events appear to be set in UTC rather than MDT.

**Comment by smarcet** [comment]
sire i am checking and calendar time zone is (GMT-06:00) Mountain Time - Denver

i imported my personal test calendar https://www.openstack.org/summit-calendar-sync/calendar/e043e40a909160498c921d4b974297a2
and saids for example

Pianos, Plumbing, and Python: How we create the world together
Monday, April 29⋅6:00 – 8:00am

original is 

Pianos, Plumbing, and Python: How we create the world together
Mon 29, 9:00am - 11:00am

Buenos Aires is 3 hours ahead of Denver, CO, USA so the showing is correct bc my calendar its showing it at BA time

u could set your calendar to show on denver time i think that its  setting

regards

**Comment by aspiers** [comment]
I had a closer look.  While the calendar has Denver timezone, I think the event times are wrong, e.g.:

```
BEGIN:VEVENT
UID:23603
DTSTART;TZID=America/Denver:20190429T030000
SEQUENCE:0
TRANSP:OPAQUE
DTEND;TZID=America/Denver:20190429T050000
LOCATION:The Colorado Convention Center - Meeting Room Level (1) - Bellco T
 heatre
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=The Colorado Convention Cen
 ter - Meeting Room Level (1) - Bellco Theatre;X-APPLE-RADIUS=49;X-TITLE=Th
 e Colorado Convention Center - Meeting Room Level (1) - Bellco Theatre:geo
 :0.000000,0.000000
GEO:0.000000;0.000000
SUMMARY:Pianos\, Plumbing\, and Python: How we create the world together
```

I'm pretty sure a keynote shouldn't start at 3am local time ;-)

**Comment by aspiers** [comment]
I should have also said that my Google Calendar is currently set to BST (+0100) and it is showing this keynote event at 10am BST, which is 3am in Denver.

**Comment by smarcet** [comment]
ok no worries i will take a look thx for the info :)

regards

**Comment by smarcet** [comment]
ok done
a fix will be released soon

regards

**Comment by smarcet** [comment]
ok fix its released now time zone is correct
my calendar it on BA time zone GMT -3 and its showing correctly to me

Pianos, Plumbing, and Python: How we create the world together
Monday, April 29⋅12:00 – 2:00pm

that is translated to denver
Monday, April 29⋅09:00am – 1100 am

bc ba is ahead 3 hours from denver

regards
