### ISSUE TITLE
Projects link in footer is broken

### ISSUE THREAD

**Issue by shaderecker** [OpenStackweb/openstack-org#177]
The "Projects" link in the website footer is broken:
https://github.com/OpenStackweb/openstack-org/blob/master/themes/openstack/templates/Layout/Includes/Navigation_Footer.ss#L6

The old link is not available anymore. Where should the link point to now, I found several possibilities?
1. https://openinfra.dev/projects/
2. https://www.openstack.org/software/project-navigator/openstack-components#openstack-services
3. https://governance.openstack.org/tc/reference/projects/

If you tell me which link you wish there, I am happy to open a pull request.

**Comment by jimmytipit** [comment]
Hi @shaderecker thanks for offering to contribute.  The correct link should be: https://openinfra.dev/projects/

**Comment by jimmytipit** [comment]
Apologies. The link should go to https://www.openstack.org/software/project-navigator/ since this is now an OpenStack specific link :)  Thanks to @iamweswilson for pointing it out!

**Comment by shaderecker** [comment]
Ok, thanks for clarifiying 😁

**Comment by shaderecker** [comment]
Hi @jimmytipit I just noticed that this link is not fixed on the actual www.openstack.org page.
Did this change not make it into production?

**Comment by iamweswilson** [comment]
Thanks for the ping @shaderecker , looks like it wasn't deployed after being merged. It was just deployed. Thanks!
