### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jimmytipit** [OpenStackweb/openstack-org#20]
We already have some API endpoints with the same names. Can you reference https://docs.google.com/document/d/1gSu0jjBg_MnPQ8aPpsadI1szHqRqbu24-3NTVF4B8KE/edit and make sure there is no overlap? Additionally, in cases where we're calling the same objects, can you follow the nomenclature we've already developed?

**Comment by smarcet** [comment]
i guess that we should look at the api nomenclature of the www site itself, although we follow the same on RS, they are not the same API :)

on the summit module you could check the routes that we are already using

summit/_config/routes.yml

 'api/v1/summits': 'SummitsApi' 

SummitAPI also manages all request to speakers , events and so


regards
