### ISSUE TITLE
phpmailer missing from requirements

### ISSUE THREAD

**Issue by fifieldt** [OpenStackweb/openstack-org#27]
Install docs don't say to install phpmailer, and it looks like the composer stuff doesn't install it correctly either:

ubuntu@trusty:/var/www/openstack$ sudo  php /var/www/openstack/framework/cli-script.php dev/build flush=1
PHP Warning:  require_once(/var/www/openstack/smtpmailer/code/vendor/class.phpmailer.php): failed to open stream: No such file or directory in /var/www/openstack/smtpmailer/code/SmtpMailer.php on line 3
PHP Fatal error:  require_once(): Failed opening required '/var/www/openstack/smtpmailer/code/vendor/class.phpmailer.php' (include_path='/var/www/openstack/vendor/openid/php-openid:/var/www/openstack/vendor/phpunit/phpunit-mock-objects:/var/www/openstack/vendor/phpunit/php-token-stream:/var/www/openstack/vendor/phpunit/php-code-coverage:/var/www/openstack/vendor/phpunit/phpunit:/var/www/openstack/vendor/symfony/yaml:.:/var/www/openstack/framework:/var/www/openstack/framework/parsers:/var/www/openstack/framework/thirdparty:.:/usr/share/php:/usr/share/pear') in /var/www/openstack/smtpmailer/code/SmtpMailer.php on line 3

**Comment by jimmytipit** [comment]
@smarcet Can you make sure this is included in the latest documentation update?

**Comment by smarcet** [comment]
PHP mailer is not longer used
closing this one
regards
